{
 "title": "BCSC Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dev",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) from requests where archived = false and 'dev' = ANY(environments) and 'bcservicescard' = ANY(dev_idps);"
    }
   ]
  },
  {
   "title": "Test",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) from requests where archived = false and 'test' = ANY(environments) and 'bcservicescard' = ANY(dev_idps);"
    }
   ]
  },
  {
   "title": "Prod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) as \"Un-Approved\" from requests where archived = false and 'prod' = ANY(environments) and 'bcservicescard' = ANY(dev_idps) and bc_services_card_approved IS NULL;"
    },
    {
     "rawSql": "select count(1) as \"Approved\" from requests where archived = false and 'prod' = ANY(environments) and 'bcservicescard' = ANY(dev_idps) and bc_services_card_approved = true;"
    }
   ]
  },
  {
   "title": "List of Un-Approved Integrations",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select id as \"ID\", project_name as \"Project\", created_at as \"Created Date\", updated_at as \"Last Updated Date\", dev_idps as \"Identity Providers\", protocol as \"Protocol\" from requests where archived = false and 'prod' = ANY(environments) \nand bc_services_card_approved IS NULL\nand exists(\n  select 1 from unnest(dev_idps) as idp where idp like 'bcservicescard%'\n) \norder by id desc;"
    }
   ]
  },
  {
   "title": "List of Approved Integrations",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select r.id as \"ID\", r.project_name as \"Project\", r.created_at as \"Created Date\", r.updated_at as \"Last Updated Date\", r.dev_idps as \"Identity Providers\", r.protocol as \"Protocol\", e.idir_user_display_name as \"Approved By\" from requests r right join events e on r.id = e.request_id where r.archived = false and 'prod' = ANY(r.environments) \nand e.event_code = 'request-update-success'\nand bceid_approved = true\nand EXISTS (\n    SELECT 1\n    FROM jsonb_array_elements(e.details->'changes') AS change\n    WHERE change->'path' @> '[\"bcServicesCardApproved\"]' and\n    change->'rhs' @> 'true'\n)\nand exists(\n  select 1 from unnest(dev_idps) as idp where idp like 'bcservicescard'\n) \norder by r.id desc;"
    }
   ]
  }
 ]
}