{
 "title": "Active Sessions & SSO Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "dev,test,prod" }
  ]
 },
 "panels": [
  {
   "title": "Active sessions (aggregator)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select date, realm_id, client_id, active_sessions as \"Active Session Count\", offline_sessions as \"Offline Session Count\" from client_sessions where $__timeFilter(date) and environment='${environment}';"
    }
   ]
  },
  {
   "title": "Logs by realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({environment=\"prod\"} |= `realmId=` | regexp \".*realmId=(?P<realmId>\\\\S+),\" [10s])) by (realmId)"
    }
   ]
  },
  {
   "title": "Top Client Events (loki)",
   "type": "table",
   "description": "See the highest event counts by client and realm and type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by (client_id, realm_id, event) (count_over_time({environment=`${environment}`} | regexp \"type=(?P<event>[^,]+).*realmId=(?P<realm_id>[^,]+).*clientId=(?P<client_id>[^,]+)\"[$__range])))"
    }
   ]
  }
 ]
}