{
 "title": "Standard Service Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DEV clients by IDP with roles",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n count( distinct   \"public\".\"client\".\"client_id\") AS \"client_id\"  ,\r\n  \"Client Scope\".\"name\" AS \"Client Scope__name\"\r\n\r\nFROM\r\n  \"public\".\"client\"\r\n \r\nLEFT JOIN \"public\".\"client_scope_client\" AS \"Client Scope Client\" ON \"public\".\"client\".\"id\" = \"Client Scope Client\".\"client_id\"\r\n  LEFT JOIN \"public\".\"client_scope\" AS \"Client Scope\" ON \"Client Scope Client\".\"scope_id\" = \"Client Scope\".\"id\"\r\n  LEFT JOIN \"public\".\"keycloak_role\" AS \"Keycloak Role\" ON \"public\".\"client\".\"id\" = \"Keycloak Role\".\"client\"\r\n  LEFT JOIN \"public\".\"user_role_mapping\" AS \"User Role Mapping\" ON \"Keycloak Role\".\"id\" = \"User Role Mapping\".\"role_id\"\r\n  LEFT JOIN \"public\".\"user_attribute\" AS \"User Attribute - User\" ON \"User Role Mapping\".\"user_id\" = \"User Attribute - User\".\"user_id\"\r\nWHERE\r\n  (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created' OR \"public\".\"client\".\"description\" = 'Manually Created to Test BCSC SIT'\r\n  )\r\n  AND (  \"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n  AND (\r\n\r\n(\"Client Scope\".\"name\" = 'bceidbasic')\r\n    OR (\"Client Scope\".\"name\" = 'bceidbasic-saml')\r\n    OR (\"Client Scope\".\"name\" = 'bceidboth')\r\n    OR (\"Client Scope\".\"name\" = 'bceidboth-saml')\r\n    OR (\"Client Scope\".\"name\" = 'bceidbusiness')\r\n    OR (\"Client Scope\".\"name\" = 'bceidbusiness-saml')\r\nOR  (\"Client Scope\".\"name\" = 'azureidir')  \r\n OR (\"Client Scope\".\"name\" = 'azureidir-saml')    \r\n OR (\"Client Scope\".\"name\" = 'githubbcgov')\r\nOR (\"Client Scope\".\"name\" = 'githubbcgov-saml')\r\n OR (\"Client Scope\".\"name\" = 'githubpublic')\r\n OR (\"Client Scope\".\"name\" = 'githubpublic-saml')\r\nOR (\"Client Scope\".\"name\" = 'idir')\r\nOR (\"Client Scope\".\"name\" = 'idir-saml') \r\nOR (\"Client Scope\".\"name\" LIKE 'bcsc%') \r\n  )\r\n\r\n  -- AND (\r\n  --    \"User Role Mapping\".\"user_id\" IS NOT NULL\r\n  -- )\r\n\r\n  group by   \"Client Scope\".\"name\" \r\n\r\n  order by   \"Client Scope\".\"name\" "
    }
   ]
  },
  { "title": "Number of Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Number of Clients DEV",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Dev Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    }
   ]
  },
  {
   "title": "Number of Clients Test",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Test Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    }
   ]
  },
  {
   "title": "Number of Clients Prod",
   "type": "stat",
   "description": "Note that CSS Team accounts are only created in PROD..so prod query is now updated",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Prod Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    }
   ]
  },
  {
   "title": "Average Number of Clients by Environment",
   "type": "stat",
   "description": "The average number of clients across the dev, test, and production environments.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Dev Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Test Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS \"Prod Count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  (\"public\".\"client\".\"realm_id\" = 'standard')\r\n \r\n   AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account')\r\n   \r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\"public\".\"client\".\"client_id\" <> 'broker')\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    (\r\n      \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n    )\r\n    OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n  )\r\n  AND (\r\n    \"public\".\"client\".\"description\" = 'CSS App Created'\r\n  )"
    }
   ]
  },
  {
   "title": "Prod - CSS Team Account",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"count\"\r\nFROM \"public\".\"client\"\r\nWHERE (\"public\".\"client\".\"realm_id\" = 'standard'\r\n   \r\n   AND (\"public\".\"client\".\"client_id\"  like  'service-account-team%')\r\n   )"
    }
   ]
  },
  { "title": "Number of Service Accounts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Service Accounts Dev",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"count\"\r\nFROM \"public\".\"client\"\r\nWHERE (\"public\".\"client\".\"realm_id\" = 'standard'\r\n   AND \"public\".\"client\".\"service_accounts_enabled\" = TRUE)"
    }
   ]
  },
  {
   "title": "Service Accounts Test",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"count\"\r\nFROM \"public\".\"client\"\r\nWHERE (\"public\".\"client\".\"realm_id\" = 'standard'\r\n   AND \"public\".\"client\".\"service_accounts_enabled\" = TRUE)"
    }
   ]
  },
  {
   "title": "Service Accounts Prod",
   "type": "stat",
   "description": "note CSS Account APIs are only created inprod",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"count\"\r\nFROM \"public\".\"client\"\r\nWHERE (\"public\".\"client\".\"realm_id\" = 'standard'\r\n   AND \"public\".\"client\".\"service_accounts_enabled\" = TRUE)"
    }
   ]
  },
  { "title": "Standard Protocol Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Dev Protocols",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"public\".\"client\".\"protocol\" AS \"protocol\",\r\n  COUNT(*) AS \"count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  \"public\".\"client\".\"realm_id\" = 'standard'\r\nAND  (\"public\".\"client\".\"client_id\" not in ('account', 'account-console','admin-cli','broker','realm-management','security-admin-console'  ))\r\nGROUP BY\r\n  \"public\".\"client\".\"protocol\"\r\nORDER BY\r\n  \"public\".\"client\".\"protocol\" ASC"
    }
   ]
  },
  {
   "title": "Test Protocols",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"public\".\"client\".\"protocol\" AS \"protocol\",\r\n  COUNT(*) AS \"count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  \"public\".\"client\".\"realm_id\" = 'standard'\r\nAND  (\"public\".\"client\".\"client_id\" not in ('account', 'account-console','admin-cli','broker','realm-management','security-admin-console'  ))\r\nGROUP BY\r\n  \"public\".\"client\".\"protocol\"\r\nORDER BY\r\n  \"public\".\"client\".\"protocol\" ASC"
    }
   ]
  },
  {
   "title": "Prod Protocols",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"public\".\"client\".\"protocol\" AS \"protocol\",\r\n  COUNT(*) AS \"count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  \"public\".\"client\".\"realm_id\" = 'standard'\r\nAND  (\"public\".\"client\".\"client_id\" not in ('account', 'account-console','admin-cli','broker','realm-management','security-admin-console'  ))\r\nGROUP BY\r\n  \"public\".\"client\".\"protocol\"\r\nORDER BY\r\n  \"public\".\"client\".\"protocol\" ASC"
    }
   ]
  },
  {
   "title": "Number of CSS Team Accounts in Standard - Client selected CSS API Account",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  }
 ]
}