{
 "title": "Service Overview Custom",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Protocol Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dev Protocol",
     "type": "table",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  \"public\".\"client\".\"protocol\" AS \"protocol\",\r\n  COUNT(*) AS \"count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  \"public\".\"client\".\"realm_id\" not in ( 'standard','idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic')\r\n  AND  (\"public\".\"client\".\"client_id\" not in ('account', 'account-console','admin-cli','broker','realm-management','security-admin-console'  ))\r\nGROUP BY\r\n  \"public\".\"client\".\"protocol\"\r\nORDER BY\r\n  \"public\".\"client\".\"protocol\" ASC"
      }
     ]
    },
    {
     "title": "Test Protocol",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 7, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  \"public\".\"client\".\"protocol\" AS \"protocol\",\r\n  COUNT(*) AS \"count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  \"public\".\"client\".\"realm_id\" not in ( 'standard','idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic')\r\n  AND  (\"public\".\"client\".\"client_id\" not in ('account', 'account-console','admin-cli','broker','realm-management','security-admin-console'  ))\r\nGROUP BY\r\n  \"public\".\"client\".\"protocol\"\r\nORDER BY\r\n  \"public\".\"client\".\"protocol\" ASC"
      }
     ]
    },
    {
     "title": "Prod Protocol",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 13, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  \"public\".\"client\".\"protocol\" AS \"protocol\",\r\n  COUNT(*) AS \"count\"\r\nFROM\r\n  \"public\".\"client\"\r\nWHERE\r\n  \"public\".\"client\".\"realm_id\" not in ( 'standard','idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic')\r\n  AND  (\"public\".\"client\".\"client_id\" not in ('account', 'account-console','admin-cli','broker','realm-management','security-admin-console'  ))\r\nGROUP BY\r\n  \"public\".\"client\".\"protocol\"\r\nORDER BY\r\n  \"public\".\"client\".\"protocol\" ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Realms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "DEV Custom Realms",
     "type": "table",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "\r\nselect count(*) \r\nfrom realm where realm.name not in ('idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic')"
      }
     ]
    },
    {
     "title": "TEST Custom Realms",
     "type": "table",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
     "targets": [
      {
       "rawSql": "\r\nselect count(*) \r\nfrom realm where realm.name not in ('idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic')"
      }
     ]
    },
    {
     "title": "PROD Custom Realms",
     "type": "table",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
     "targets": [
      {
       "rawSql": "\r\nselect count(*) \r\nfrom realm where realm.name not in ('idir','azureidir','bceidbusiness','bceidboth','github','master','bceidbasic')"
      }
     ]
    }
   ]
  },
  {
   "title": "Avg Number of Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dev Avg Clients",
     "type": "table",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      COUNT(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        (\r\n          \"public\".\"client\".\"realm_id\" not in (\r\n            'standard',\r\n            'idir',\r\n            'azureidir',\r\n            'bceidbusiness',\r\n            'bceidboth',\r\n            'github',\r\n            'master',\r\n            'bceidbasic'\r\n          )\r\n        )\r\n       \r\n    OR (\"public\".\"client\".\"realm_id\" IS NULL)\r\n      )\r\n     \r\n   AND (\r\n        (\"public\".\"client\".\"client_id\" <> 'account')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n        OR (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'broker')\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n        )\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n        )\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    },
    {
     "title": "Test Avg Clients",
     "type": "table",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      COUNT(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        (\r\n          \"public\".\"client\".\"realm_id\" not in (\r\n            'standard',\r\n            'idir',\r\n            'azureidir',\r\n            'bceidbusiness',\r\n            'bceidboth',\r\n            'github',\r\n            'master',\r\n            'bceidbasic'\r\n          )\r\n        )\r\n       \r\n    OR (\"public\".\"client\".\"realm_id\" IS NULL)\r\n      )\r\n     \r\n   AND (\r\n        (\"public\".\"client\".\"client_id\" <> 'account')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n        OR (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'broker')\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n        )\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n        )\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    },
    {
     "title": "Prod Avg Clients",
     "type": "table",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      COUNT(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        (\r\n          \"public\".\"client\".\"realm_id\" not in (\r\n            'standard',\r\n            'idir',\r\n            'azureidir',\r\n            'bceidbusiness',\r\n            'bceidboth',\r\n            'github',\r\n            'master',\r\n            'bceidbasic'\r\n          )\r\n        )\r\n       \r\n    OR (\"public\".\"client\".\"realm_id\" IS NULL)\r\n      )\r\n     \r\n   AND (\r\n        (\"public\".\"client\".\"client_id\" <> 'account')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'account-console')\r\n        OR (\"public\".\"client\".\"client_id\" <> 'admin-cli')\r\n        OR (\"public\".\"client\".\"client_id\" IS NULL)\r\n        OR (\"public\".\"client\".\"client_id\" <> 'broker')\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'realm-management'\r\n        )\r\n        OR (\r\n          \"public\".\"client\".\"client_id\" <> 'security-admin-console'\r\n        )\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    }
   ]
  },
  {
   "title": "Avg Number of Service Accounts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dev Service Accounts Avg",
     "type": "table",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      count(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        \"public\".\"client\".\"realm_id\" not in (\r\n          'standard',\r\n          'idir',\r\n          'azureidir',\r\n          'bceidbusiness',\r\n          'bceidboth',\r\n          'github',\r\n          'master',\r\n          'bceidbasic'\r\n        )\r\n       \r\n   AND \"public\".\"client\".\"service_accounts_enabled\" = TRUE\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    },
    {
     "title": "Test Service Accounts Avg",
     "type": "table",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      count(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        \"public\".\"client\".\"realm_id\" not in (\r\n          'standard',\r\n          'idir',\r\n          'azureidir',\r\n          'bceidbusiness',\r\n          'bceidboth',\r\n          'github',\r\n          'master',\r\n          'bceidbasic'\r\n        )\r\n       \r\n   AND \"public\".\"client\".\"service_accounts_enabled\" = TRUE\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    },
    {
     "title": "Service Accounts Avg",
     "type": "table",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  AVG(\"source\".\"count\") AS \"avg\"\r\nFROM\r\n  (\r\n    SELECT\r\n      \"public\".\"client\".\"realm_id\" AS \"realm_id\",\r\n      count(*) AS \"count\"\r\n    FROM\r\n      \"public\".\"client\"\r\n   \r\nWHERE\r\n      (\r\n        \"public\".\"client\".\"realm_id\" not in (\r\n          'standard',\r\n          'idir',\r\n          'azureidir',\r\n          'bceidbusiness',\r\n          'bceidboth',\r\n          'github',\r\n          'master',\r\n          'bceidbasic'\r\n        )\r\n       \r\n   AND \"public\".\"client\".\"service_accounts_enabled\" = TRUE\r\n      )\r\n   \r\nGROUP BY\r\n      \"public\".\"client\".\"realm_id\"\r\n   \r\nORDER BY\r\n      count desc\r\n  ) AS \"source\""
      }
     ]
    }
   ]
  }
 ]
}