{
 "title": "BCeID Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dev",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) as \"BCeID Basic\" from requests where archived = false and 'dev' = ANY(environments) and 'bceidbasic' = ANY(dev_idps);"
    },
    {
     "rawSql": "select count(1) as \"BCeID Business\" from requests where archived = false and 'dev' = ANY(environments) and 'bceidbusiness' = ANY(dev_idps);"
    },
    {
     "rawSql": "select count(1) as \"BCeID Both\" from requests where archived = false and 'dev' = ANY(environments) and 'bceidboth' = ANY(dev_idps);"
    }
   ]
  },
  {
   "title": "Test",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) as \"BCeID Basic\" from requests where archived = false and 'test' = ANY(environments) and 'bceidbasic' = ANY(dev_idps);"
    },
    {
     "rawSql": "select count(1) as \"BCeID Business\" from requests where archived = false and 'test' = ANY(environments) and 'bceidbusiness' = ANY(dev_idps);"
    },
    {
     "rawSql": "select count(1) as \"BCeID Both\" from requests where archived = false and 'test' = ANY(environments) and 'bceidboth' = ANY(dev_idps);"
    }
   ]
  },
  {
   "title": "Prod (un-approved)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) as \"BCeID Basic\" from requests where archived = false and 'prod' = ANY(environments) and 'bceidbasic' = ANY(dev_idps) and bceid_approved = false;"
    },
    {
     "rawSql": "select count(1) as \"BCeID Business\" from requests where archived = false and 'prod' = ANY(environments) and 'bceidbusiness' = ANY(dev_idps) and bceid_approved = false;"
    },
    {
     "rawSql": "select count(1) as \"BCeID Both\" from requests where archived = false and 'prod' = ANY(environments) and 'bceidboth' = ANY(dev_idps) and bceid_approved = false;"
    }
   ]
  },
  {
   "title": "Prod (approved)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) as \"BCeID Basic\" from requests where archived = false and 'prod' = ANY(environments) and 'bceidbasic' = ANY(dev_idps) and bceid_approved = true;"
    },
    {
     "rawSql": "select count(1) as \"BCeID Business\" from requests where archived = false and 'prod' = ANY(environments) and 'bceidbusiness' = ANY(dev_idps) and bceid_approved = true;"
    },
    {
     "rawSql": "select count(1) as \"BCeID Both\" from requests where archived = false and 'prod' = ANY(environments) and 'bceidboth' = ANY(dev_idps) and bceid_approved = true;"
    }
   ]
  },
  {
   "title": "List of Un-Approved Integrations",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select id as \"ID\", project_name as \"Project\", created_at as \"Created Date\", updated_at as \"Last Updated Date\", dev_idps as \"Identity Providers\", protocol as \"Protocol\" from requests where archived = false and 'prod' = ANY(environments) \nand bceid_approved = false\nand exists(\n  select 1 from unnest(dev_idps) as idp where idp like 'bceid%'\n) \norder by id desc;"
    }
   ]
  },
  {
   "title": "List of Approved Integrations",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select r.id as \"ID\", r.project_name as \"Project\", r.created_at as \"Created Date\", r.updated_at as \"Last Updated Date\", r.dev_idps as \"Identity Providers\", r.protocol as \"Protocol\", e.idir_user_display_name as \"Approved By\" from requests r right join events e on r.id = e.request_id where r.archived = false and 'prod' = ANY(r.environments) \nand e.event_code = 'request-update-success'\nand bceid_approved = true\nand EXISTS (\n    SELECT 1\n    FROM jsonb_array_elements(e.details->'changes') AS change\n    WHERE change->'path' @> '[\"bceidApproved\"]' and\n    change->'lhs' @> 'false' and\n    change->'rhs' @> 'true'\n)\nand exists(\n  select 1 from unnest(dev_idps) as idp where idp like 'bceid%'\n) \norder by r.id desc;"
    }
   ]
  },
  {
   "title": "BCeID Extract",
   "type": "table",
   "description": "Query for bceid information extract",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select r.project_name as \"Project\", array_to_string(r.dev_idps, ',') as \"Identity Providers\", array_to_string(r.prod_valid_redirect_uris, ',') as \"Production URIs\", r.idir_user_display_name, u.idir_email, r.bceid_approved as \"Production Approved\"\r\nfrom requests r \r\njoin users u on u.id = r.user_id\r\nwhere r.archived = false and 'prod' = ANY(r.environments)\r\nand exists(\r\n  select 1 from unnest(dev_idps) as idp where idp like 'bceid%'\r\n) \r\norder by r.id desc;"
    }
   ]
  }
 ]
}