{
 "title": "Client Satisfaction /Survey Results",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Overall Average",
   "type": "table",
   "description": "Since 2023-10-20 ",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select avg(s.rating),count(s.id)\r\nfrom users u, surveys s\r\nwhere u.id=s.user_id"
    }
   ]
  },
  { "title": "Satisfaction Rating Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Survey Results Average by Feature",
   "type": "table",
   "description": "Score is out of 5",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select trigger_event,count(s.id), min(s.created_at),max(s.created_at),avg(s.rating)\r\nfrom users u, surveys s\r\nwhere u.id=s.user_id\r\ngroup by trigger_event;"
    }
   ]
  },
  {
   "title": "Satisfaction  Text",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "select s.* \r\nfrom users u, surveys s \r\nwhere u.id=s.user_id \r\nand s.message  != '  '\r\nand s.message  != ''\r\nand s.message  != ' '"
    }
   ]
  },
  {
   "title": "List of emails that submitted survey",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select distinct u.idir_email\r\nfrom users u, surveys s\r\nwhere u.id=s.user_id;"
    }
   ]
  },
  {
   "title": "Satisfaction Results",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select s.* \r\nfrom users u, surveys s \r\nwhere u.id=s.user_id \r\norder by s.created_at, s.message desc;"
    }
   ]
  },
  {
   "title": "Total integrations created or updated after Oct 23, 2023",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Integrations created after Oct 23, 2023",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "select count(*)\r\nfrom requests r\r\nwhere\r\nr.created_at  >= timestamp with time zone '2023-10-23 00:00:00.000Z'\r\n"
      }
     ]
    },
    {
     "title": "Total Integrations Updated after Oct 23, 2023",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "select count(*)\r\nfrom requests r\r\nwhere\r\nr.updated_at  >= timestamp with time zone '2023-10-23 00:00:00.000Z'\r\n"
      }
     ]
    }
   ]
  }
 ]
}