{
 "title": "End Users",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Standard Integrations by End user Category",
   "type": "barchart",
   "description": "All integrations that are active",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with unnested as (\r\n  select unnest(primary_end_users) as type from requests where archived = false \r\n)\r\nselect count(type), type from unnested group by type;"
    }
   ]
  },
  {
   "title": "Details LivingInBC",
   "type": "table",
   "description": "All integrations that are active",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select id, project_name, project_lead\r\nfrom requests \r\n\r\nwhere 'livingInBC' = ANY(primary_end_users)\r\nand  archived = false \r\n"
    }
   ]
  },
  {
   "title": "Breakdown of others",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select primary_end_users_other\r\nfrom requests where 'other' = ANY(primary_end_users)\r\nand primary_end_users_other != ' '\r\nand primary_end_users_other != ''\r\nand primary_end_users_other != '  '\r\n\r\nAND  archived = false \r\norder by primary_end_users_other  desc;"
    }
   ]
  },
  {
   "title": "Details BCGovEmployee",
   "type": "table",
   "description": "All integrations that are active",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select id, project_name, project_lead\r\nfrom requests \r\n\r\nwhere 'bcGovEmployees' = ANY(primary_end_users)\r\nand  archived = false \r\n"
    }
   ]
  },
  {
   "title": "Details businessInBC",
   "type": "table",
   "description": "All integrations that are active",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select id, project_name, project_lead\r\nfrom requests \r\n\r\nwhere 'businessInBC' = ANY(primary_end_users)\r\nand  archived = false \r\n"
    }
   ]
  }
 ]
}