{
 "title": "Standard Integration Details",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "idp",
    "label": "Identity Provider",
    "query": "idir,azureidir,bceidbasic, bceidbusiness,bceidboth,githubpublic,githubbcgov"
   }
  ]
 },
 "panels": [
  {
   "title": "Integrations Roles vs no Roles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Standard Integrations by IDP",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT id, environments,dev_idps,test_idps,prod_idps, auth_type\r\nFROM requests \r\nWHERE archived is not true\r\nAND status !='draft'\r\nand api_service_account is not true\r\nand auth_type !='service-account'\r\norder by dev_idps asc "
      }
     ]
    },
    {
     "title": "Standard Integrations by IDP FIlter",
     "type": "table",
     "gridPos": { "h": 6, "w": 13, "x": 8, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT *\r\nFROM requests \r\nWHERE archived is not true\r\nAND status !='draft'\r\nand api_service_account is not true\r\nand auth_type !='service-account'\r\norder by dev_idps asc \r\n"
      }
     ]
    },
    {
     "title": "Dev total active integrations",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(r.id)\r\nFROM requests r\r\nWHERE r.archived is not true\r\nAND r.status !='draft'\r\nand r.api_service_account is not true\r\nand r.auth_type !='service-account'\r\n\r\n\r\n\r\n"
      },
      {
       "sql": {
        "columns": [
         {
          "parameters": [],
          "type": "function"
         }
        ],
        "groupBy": [
         { "property": { "type": "string" }, "type": "groupBy" }
        ],
        "limit": 50
       },
       "table": "request_roles"
      }
     ]
    },
    {
     "title": "Dev total active integrations with roles",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(distinct r.id)\r\nFROM  requests r \r\nWHERE  exists (SELECT rr.request_id FROM request_roles rr WHERE rr.request_id=r.id)\r\nAND r.archived is not true\r\nAND r.status !='draft'\r\nand r.api_service_account is not true\r\nand r.auth_type !='service-account'\r\n\r\n\r\n\r\n"
      },
      {
       "sql": {
        "columns": [
         {
          "parameters": [],
          "type": "function"
         }
        ],
        "groupBy": [
         { "property": { "type": "string" }, "type": "groupBy" }
        ],
        "limit": 50
       },
       "table": "request_roles"
      }
     ]
    },
    {
     "title": "Dev total active integrations with NO roles",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(distinct r.id)\r\nFROM  requests r \r\nWHERE  NOT exists (SELECT rr.request_id FROM request_roles rr WHERE rr.request_id=r.id)\r\nAND r.archived is not true\r\nAND r.status !='draft'\r\nand r.api_service_account is not true\r\nand r.auth_type !='service-account'\r\n\r\n\r\n\r\n"
      },
      {
       "sql": {
        "columns": [
         {
          "parameters": [],
          "type": "function"
         }
        ],
        "groupBy": [
         { "property": { "type": "string" }, "type": "groupBy" }
        ],
        "limit": 50
       },
       "table": "request_roles"
      }
     ]
    }
   ]
  },
  { "title": "Filter in Query by IDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Standard Integrations by IDP with filter in Query",
   "type": "barchart",
   "description": "please see query for which idp is flitered",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with list as (SELECT    ARRAY_TO_STRING(dev_idps, ', ') as dev_idps\r\nFROM requests \r\nWHERE archived is not true\r\nAND status !='draft'\r\nand api_service_account is not true\r\nand auth_type !='service-account'\r\n\r\n ) select count (*) as total, dev_idps \r\n \r\n FROM list\r\n where dev_idps like '%${idp}%'\r\n group by dev_idps"
    }
   ]
  },
  {
   "title": "Total Standard Integrations by IDP with filter in Query",
   "type": "gauge",
   "description": "please see query for which idp is flitered",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with list as (SELECT    ARRAY_TO_STRING(dev_idps, ', ') as dev_idps\r\nFROM requests \r\nWHERE archived is not true\r\nAND status !='draft'\r\nand api_service_account is not true\r\nand auth_type !='service-account'\r\n\r\n ) select count (*) as total\r\n \r\n FROM list\r\n where dev_idps like '%${idp}%'\r\n"
    }
   ]
  },
  {
   "title": "Integrations by IDP filtered -  roles vs no roles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "total active integrations",
   "type": "stat",
   "description": "please see query for which idp is flitered",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with list as (SELECT    ARRAY_TO_STRING(dev_idps, ', ') as dev_idps\r\nFROM requests \r\nWHERE archived is not true\r\nAND status !='draft'\r\nand api_service_account is not true\r\nand auth_type !='service-account'\r\n\r\n ) select count (*) as total\r\n \r\n FROM list\r\n where dev_idps like '%${idp}%'\r\n"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "request_roles"
    }
   ]
  },
  {
   "title": "total active integrations with roles",
   "type": "stat",
   "description": "please see query for which idp is flitered",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with list as (SELECT    ARRAY_TO_STRING(r.dev_idps, ', ') as dev_idps\r\nFROM requests r\r\nWHERE r.archived is not true\r\nAND r.status !='draft'\r\nand r.api_service_account is not true\r\nand r.auth_type !='service-account'\r\nAND exists (SELECT rr.request_id FROM request_roles rr WHERE rr.request_id=r.id)\r\n ) select count (*) as total\r\n \r\n FROM list\r\n where dev_idps like '%${idp}%'\r\n\r\n"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "request_roles"
    }
   ]
  },
  {
   "title": " total active integrations with No roles",
   "type": "stat",
   "description": "please see query for which idp is flitered",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with list as (SELECT    ARRAY_TO_STRING(r.dev_idps, ', ') as dev_idps\r\nFROM requests r\r\nWHERE r.archived is not true\r\nAND r.status !='draft'\r\nand r.api_service_account is not true\r\nand r.auth_type !='service-account'\r\nAND NOT exists (SELECT rr.request_id FROM request_roles rr WHERE rr.request_id=r.id)\r\n ) select count (*) as total\r\n \r\n FROM list\r\n where dev_idps like '%${idp}%'\r\n\r\n"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "request_roles"
    }
   ]
  },
  {
   "title": "details active integrations with roles",
   "type": "table",
   "description": "please see query for which idp is flitered",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with list as (SELECT    ARRAY_TO_STRING(r.dev_idps, ', ') as dev_idps\r\nFROM requests r\r\nWHERE r.archived is not true\r\nAND r.status !='draft'\r\nand r.api_service_account is not true\r\nand r.auth_type !='service-account'\r\nAND exists (SELECT rr.request_id FROM request_roles rr WHERE rr.request_id=r.id)\r\n ) select count (*) as total, dev_idps\r\n \r\n FROM list\r\n where dev_idps like '%${idp}%'\r\n group by dev_idps\r\n order by total desc\r\n\r\n"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "request_roles"
    }
   ]
  },
  {
   "title": "details active integrations with NO roles",
   "type": "table",
   "description": "please see query for which idp is flitered",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with list as (SELECT    ARRAY_TO_STRING(r.dev_idps, ', ') as dev_idps\r\nFROM requests r\r\nWHERE r.archived is not true\r\nAND r.status !='draft'\r\nand r.api_service_account is not true\r\nand r.auth_type !='service-account'\r\nAND not exists (SELECT rr.request_id FROM request_roles rr WHERE rr.request_id=r.id)\r\n ) select count (*) as total, dev_idps\r\n \r\n FROM list\r\n where dev_idps like '%${idp}%'\r\n group by dev_idps\r\n order by total desc\r\n\r\n"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "request_roles"
    }
   ]
  },
  {
   "title": "active integrations details",
   "type": "table",
   "description": "please see query for which idp is flitered",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with list as (SELECT    ARRAY_TO_STRING(dev_idps, ', ') as dev_idps\r\nFROM requests \r\nWHERE archived is not true\r\nAND status !='draft'\r\nand api_service_account is not true\r\nand auth_type !='service-account'\r\n\r\n ) select count (*) as total, dev_idps \r\n \r\n FROM list\r\n where dev_idps like '%${idp}%'\r\n group by dev_idps\r\n order by total desc"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "request_roles"
    }
   ]
  }
 ]
}