{
 "title": "Production Clients with Logins in the last month",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Count of Active Production Clients ",
   "type": "table",
   "description": "Shows production clients with browser login events in the last 30 days",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select client_id, project_name from requests where archived = false and 'prod' = any(environments) and auth_type in ('browser-login', 'both') and status='applied'\r\norder by client_id"
    },
    {
     "rawSql": "select distinct client_id from client_events_with_idp e where e.environment = 'prod' and $__timeFilter(e.date) and exists (\r\n  select 1 from client_events_with_idp e2 where e2.client_id = e.client_id and $__timeFilter(e2.date)\r\n  and e2.event_type in ('LOGIN', 'CLIENT_LOGIN', 'REFRESH_TOKEN')\r\n) and realm_id = 'standard'\r\n\r\nUNION ALL\r\nSelect null"
    }
   ]
  },
  {
   "title": "Count of Active Production Clients (non SA)",
   "type": "stat",
   "description": "Shows production clients with login or refresh token events, excluding service accounts",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select client_id from requests where archived = false and 'prod' = any(environments) and auth_type in ('browser-login', 'both') and status='applied'\r\n"
    },
    {
     "rawSql": "select distinct client_id from client_events_with_idp e where e.environment = 'prod' and $__timeFilter(e.date) and exists (\r\n  select 1 from client_events_with_idp e2 where e2.client_id = e.client_id and $__timeFilter(e2.date)\r\n  and e2.event_type in ('LOGIN', 'REFRESH_TOKEN')\r\n) and realm_id = 'standard'\r\n\r\nUNION ALL\r\nSelect null"
    }
   ]
  },
  {
   "title": "Inactive Production Clients ",
   "type": "stat",
   "description": "Shows production clients with no login or refresh token events excluding service accounts",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select client_id, project_name from requests where archived = false and 'prod' = any(environments) and auth_type in ('browser-login', 'both') and status='applied'\r\norder by client_id"
    },
    {
     "rawSql": "select distinct client_id, 1 as \"exists\" from client_events_with_idp e where e.environment = 'prod' and $__timeFilter(e.date) and exists (\r\n  select 1 from client_events_with_idp e2 where e2.client_id = e.client_id and $__timeFilter(e2.date)\r\n  and e2.event_type in ('LOGIN', 'CLIENT_LOGIN', 'REFRESH_TOKEN')\r\n) and realm_id = 'standard'\r\n\r\nUNION ALL\r\nSelect null, 1"
    }
   ]
  },
  {
   "title": "Inactive Production Clients ",
   "type": "table",
   "description": "Shows production clients with browser login events in the last 30 days",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select client_id, project_name from requests where archived = false and 'prod' = any(environments) and auth_type in ('browser-login', 'both') and status='applied'\r\norder by client_id"
    },
    {
     "rawSql": "select distinct client_id, 1 as \"exists\" from client_events_with_idp e where e.environment = 'prod' and $__timeFilter(e.date) and exists (\r\n  select 1 from client_events_with_idp e2 where e2.client_id = e.client_id and $__timeFilter(e2.date)\r\n  and e2.event_type in ('LOGIN', 'CLIENT_LOGIN', 'REFRESH_TOKEN')\r\n) and realm_id = 'standard'\r\n\r\nUNION ALL\r\nSelect null, 1"
    }
   ]
  },
  {
   "title": "Total non SA Production Clients ",
   "type": "stat",
   "description": "Shows production clientsthat are not service accounts",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(client_id) from requests where archived = false and 'prod' = any(environments) and auth_type in ('browser-login', 'both') and status='applied'"
    }
   ]
  }
 ]
}