{
 "title": "Resource Usage Analysis",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total sessions",
   "type": "timeseries",
   "description": "Active session counts by hour",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "-- Group together all client and realm entries in the same hour. Session counts run every hour on the hour.\r\nselect date_trunc('hour', date), sum(active_sessions) from client_sessions where $__timeFilter(date) and environment = 'prod' group by date_trunc('hour', date);"
    }
   ]
  },
  {
   "title": "Token Refresh per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', date), sum(count)::float / (60*60*24) as \"Refresh per second\" from client_events_with_idp where (event_type='REFRESH_TOKEN' or event_type='REFRESH_TOKEN_ERROR') and environment = 'prod' group by date;"
    }
   ]
  },
  {
   "title": "User Logins per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 7 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', date) AS time, sum(count)::float / (60*60*24) as \"User Logins per second\" from client_events_with_idp where (event_type='LOGIN' or event_type='LOGIN_ERROR') and $__timeFilter(date) and environment='prod' group by date;"
    }
   ]
  },
  {
   "title": "Client Logins per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', date), sum(count)::float / (60*60*24) as \"Client Logins per second\" from client_events_with_idp where (event_type='CLIENT_LOGIN' or event_type='CLIENT_LOGIN_ERROR') and environment = 'prod' group by date;"
    }
   ]
  }
 ]
}