{
 "title": "Login Overview",
 "description": "Overview of login events or users and service accounts",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "dev,test,prod" }
  ]
 },
 "panels": [
  {
   "title": "Total User Login Events",
   "type": "stat",
   "description": "Total Events for the environment and time range",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(count) as \"Total Logins\" from client_events_with_idp where environment='${environment}' and event_type in ('LOGIN') and $__timeFilter(date);"
    }
   ]
  },
  {
   "title": "User Login Events Over Time",
   "type": "timeseries",
   "description": "Login events per day in the provided date range.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select date, sum(count) as \"Total Logins\" from client_events_with_idp where environment='${environment}' and event_type in ('LOGIN') and $__timeFilter(date) group by date;"
    }
   ]
  },
  {
   "title": "Total Service Account Authentications",
   "type": "stat",
   "description": "Total Service Account Authentications By Date",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(count) as \"Total Logins\" from client_events_with_idp where environment='${environment}' and event_type in ('CLIENT_LOGIN') and $__timeFilter(date);"
    }
   ]
  },
  {
   "title": "Total Service Account Authentications Over Time",
   "type": "timeseries",
   "description": "Total Service Account Authentications By Date",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "select date, sum(count) as \"Total Logins\" from client_events_with_idp where environment='${environment}' and event_type in ('CLIENT_LOGIN') and $__timeFilter(date) group by date;\r\n-- select date, realm_id, sum(count) as \"Total Logins\" from client_events where environment='prod' and event_type in ('CLIENT_LOGIN') and $__timeFilter(date) group by date, realm_id;\r\n"
    }
   ]
  },
  {
   "title": "Total Service Account Authentications Over Time By client ID",
   "type": "timeseries",
   "description": "Total Service Account Authentications By Date and client ID ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select date, client_id, sum(count) as \"Total Logins\" from client_events_with_idp where environment='${environment}' and event_type in ('CLIENT_LOGIN') and $__timeFilter(date)  group by date, client_id;\r\n-- select date, realm_id, sum(count) as \"Total Logins\" from client_events where environment='prod' and event_type in ('CLIENT_LOGIN') and $__timeFilter(date) group by date, realm_id;\r\n"
    }
   ]
  },
  {
   "title": "Total User Authentications Over Time By client ID",
   "type": "timeseries",
   "description": "Total User Authentications By Date and client ID ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select date, client_id, sum(count) as \"Total Logins\" from client_events_with_idp where environment='${environment}' and event_type in ('LOGIN') and $__timeFilter(date)  group by date, client_id;\r\n-- select date, realm_id, sum(count) as \"Total Logins\" from client_events where environment='prod' and event_type in ('CLIENT_LOGIN') and $__timeFilter(date) group by date, realm_id;\r\n"
    }
   ]
  }
 ]
}