{
 "title": "Service Overview",
 "description": "Master custom realm dashboard ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "excludedRealms",
    "label": "Custom Realms",
    "query": "idir,azureidir,bceidbusiness,bceidboth,github,master,bceidbasic,standard,otp"
   },
   { "name": "ds", "label": "Datasource", "query": "grafana-postgresql-datasource" },
   { "name": "env", "label": "Environment", "query": "dev,test,prod" }
  ]
 },
 "panels": [
  {
   "title": "Number of Custom Realms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from realm where realm.name not in (${excludedRealms}) and realm.enabled = true"
    }
   ]
  },
  {
   "title": "Number of Standard Realm Clients",
   "type": "stat",
   "description": "A count of the clients in the standard realm",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(client_id) from client where description = 'CSS App Created'"
    }
   ]
  },
  {
   "title": "Sessions By Realm",
   "type": "table",
   "description": "The last snapshot of active sessions by realm, which is taken each hour.  Realms with no sessions are not included.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "with most_recent_sessions as (\r\n  -- Colected every hour\r\n  select * from client_sessions where date > now() - interval '60 minute'\r\n)\r\nSELECT\r\n    realm_id,\r\n    sum(active_sessions) as \"Regular Sessions\",\r\n    sum(offline_sessions) as \"Offline Sessions\"\r\nFROM most_recent_sessions \r\nWHERE (realm_id not in (${excludedRealms}) or realm_id = 'standard')\r\nAND environment = '${env}'\r\nGROUP BY realm_id\r\nORDER BY \"Regular Sessions\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Realms with no sessions",
   "type": "table",
   "description": "Realms with no sessions. This does not mean they are unused, just they have no user sessions in the past hour. They may use service accounts, for example, like apigw.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select realm.name from realm where realm.name not in (${excludedRealms}) and realm.enabled = true"
    },
    {
     "rawSql": "with most_recent_sessions as (\r\n  -- Colected every hour\r\n  select * from client_sessions where date > now() - interval '60 minute'\r\n)\r\nSELECT\r\n    distinct realm_id as name, 1 as agg_field\r\nFROM most_recent_sessions \r\nWHERE (realm_id not in (${excludedRealms}) or realm_id = 'standard')\r\nAND environment = '${env}'"
    }
   ]
  },
  {
   "title": "Custom Realms using service accounts",
   "type": "table",
   "description": "Shows the number of clients with service accounts enabled in each custom realm",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "with clients_with_service_accounts as (\r\n  SELECT\r\n      realm_id,\r\n      count(*) AS \"count\"\r\n    FROM\r\n      client\r\n    WHERE realm_id not in (${excludedRealms})\r\n    AND service_accounts_enabled = TRUE\r\n    GROUP BY realm_id\r\n)\r\nSELECT\r\n  realm_id, count as \"Clients with Service Accounts\"\r\nFROM clients_with_service_accounts\r\nGROUP BY realm_id, count\r\nORDER BY count desc;"
    }
   ]
  }
 ]
}