{
 "title": "Login Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "dev,test,prod" }
  ]
 },
 "panels": [
  {
   "title": "Total logins over time",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select sum(login) + sum(client_login) as total_logins, date from sso_stats where date > NOW() - INTERVAL '30 days' group by date\norder by date desc;"
    }
   ]
  },
  {
   "title": "Total Logins (new)",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select to_char(date::date, 'YYYY-MM-DD') AS event_date, sum(count) as \"Total Logins\" from client_events where environment='${environment}' and event_type in ('CLIENT_LOGIN', 'LOGIN') and $__timeFilter(date) group by date;"
    }
   ]
  },
  { "title": "Total Logins Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Number of Logins Non Production since Aug 31 2023",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"public\".\"sso_stats\".\"namespace\" AS \"namespace\",\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\"public\".\"sso_stats\".\"login\" IS NOT NULL)\n \n   AND (\n    (\"public\".\"sso_stats\".\"namespace\" = 'e4ca1d-dev')\n   \n    OR (\"public\".\"sso_stats\".\"namespace\" = 'e4ca1d-test')\n  )\nGROUP BY\n  \"public\".\"sso_stats\".\"namespace\"\nORDER BY\n  \"public\".\"sso_stats\".\"namespace\" ASC"
    }
   ]
  },
  {
   "title": "Total Number of Logins Production since Sept 1 2023",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\"public\".\"sso_stats\".\"login\" IS NOT NULL)\n \n   AND (\"public\".\"sso_stats\".\"namespace\" = 'e4ca1d-prod' OR \"public\".\"sso_stats\".\"namespace\" IS NULL OR (\"public\".\"sso_stats\".\"namespace\" = ''))\n       AND \"public\".\"sso_stats\".\"date\" >= timestamp with time zone '2023-09-01 00:00:00.000Z'"
    }
   ]
  },
  {
   "title": "Total Logins Graph (new)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "rawSql": "select date, sum(count) as \"Total Logins\" from client_events where environment='${environment}' and event_type in ('CLIENT_LOGIN', 'LOGIN') and $__timeFilter(date) group by date;"
    }
   ]
  },
  {
   "title": "Total Number of Logins Production since May 2022",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\"public\".\"sso_stats\".\"login\" IS NOT NULL)\n \n   AND (\"public\".\"sso_stats\".\"namespace\" = 'e4ca1d-prod' OR \"public\".\"sso_stats\".\"namespace\" IS NULL OR (\"public\".\"sso_stats\".\"namespace\" = ''))"
    }
   ]
  },
  { "title": "Total Logins last 30 days", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Logins Last 30 Days From SSO Stats DEV",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"public\".\"sso_stats\".\"date\" AS \"date\",\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\n    \"public\".\"sso_stats\".\"date\" >= CAST((NOW() + INTERVAL '-30 day') AS date)\n  )\n \n   AND (\"public\".\"sso_stats\".\"date\" < CAST(NOW() AS date))\n  AND (\"public\".\"sso_stats\".\"namespace\" = 'e4ca1d-dev' )\nGROUP BY\n  \"public\".\"sso_stats\".\"date\"\nORDER BY\n  \"public\".\"sso_stats\".\"date\" ASC"
    }
   ]
  },
  {
   "title": "Logins Last 30 Days From SSO Stats TEST",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"public\".\"sso_stats\".\"date\" AS \"date\",\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\n    \"public\".\"sso_stats\".\"date\" >= CAST((NOW() + INTERVAL '-30 day') AS date)\n  )\n \n   AND (\"public\".\"sso_stats\".\"date\" < CAST(NOW() AS date))\n  AND (\"public\".\"sso_stats\".\"namespace\" = 'e4ca1d-test' )\nGROUP BY\n  \"public\".\"sso_stats\".\"date\"\nORDER BY\n  \"public\".\"sso_stats\".\"date\" ASC"
    }
   ]
  },
  {
   "title": "Logins Last 30 Days From SSO Stats PROD",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"public\".\"sso_stats\".\"date\" AS \"date\",\n  SUM(\"public\".\"sso_stats\".\"login\") AS \"sum\"\nFROM\n  \"public\".\"sso_stats\"\nWHERE\n  (\n    \"public\".\"sso_stats\".\"date\" >= CAST((NOW() + INTERVAL '-30 day') AS date)\n  )\n \n   AND (\"public\".\"sso_stats\".\"date\" < CAST(NOW() AS date))\n  AND (\"public\".\"sso_stats\".\"namespace\" = 'e4ca1d-prod' OR \"public\".\"sso_stats\".\"namespace\" IS NULL  OR (\"public\".\"sso_stats\".\"namespace\" = ''))\nGROUP BY\n  \"public\".\"sso_stats\".\"date\"\nORDER BY\n  \"public\".\"sso_stats\".\"date\" ASC"
    }
   ]
  }
 ]
}