{
 "title": "Analysis Client Redirects",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Clients impacted by wildcard",
   "type": "table",
   "description": "In the coming update having a * wildcard without an http(s) domain will cause issues. These clients are likely to be impacted, as they are using * in dev/test and a custom scheme in prod.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    client_id,\r\n    dev_valid_redirect_uris,\r\n    test_valid_redirect_uris,\r\n    prod_valid_redirect_uris,\r\n    archived\r\nFROM\r\n    requests\r\nWHERE ('*' = ANY (dev_valid_redirect_uris)\r\n    OR '*' = ANY (test_valid_redirect_uris))\r\nAND 'prod' = ANY(environments)\r\nAND archived = false\r\n-- AND EXISTS (\r\n--     SELECT\r\n--         1\r\n--     FROM\r\n--         unnest(prod_valid_redirect_uris) AS url\r\n--     WHERE\r\n--         url NOT ILIKE 'http%'\r\n--         AND url != '');"
    }
   ]
  },
  {
   "title": "Custom Clients using wildcard *",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "Please take look here\n\nhttps://sso-grafana.apps.gold.devops.gov.bc.ca/d/cb745075-94a9-445c-961a-0b5fd9f388b3/clients-with-2a-in-redirects?orgId=1"
   }
  },
  {
   "title": "Env Total Clients impacted by wildcard ",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(dev_valid_redirect_uris) as dev_integrations,\r\n    count(test_valid_redirect_uris) as test_integrations\r\n \r\nFROM\r\n    requests\r\nWHERE ('*' = ANY (dev_valid_redirect_uris)\r\n    OR '*' = ANY (test_valid_redirect_uris))\r\nAND 'prod' = ANY(environments)\r\nAND archived = false\r\n-- AND EXISTS (\r\n--     SELECT\r\n--         1\r\n--     FROM\r\n--         unnest(prod_valid_redirect_uris) AS url\r\n--     WHERE\r\n--         url NOT ILIKE 'http%'\r\n--         AND url != '');"
    }
   ]
  },
  {
   "title": "Redirect list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select * from requests LIMIT 10"
    }
   ]
  }
 ]
}