{
 "title": "CSS API Usage Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Count of hits at 5 min intervals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('minute', \"timestamp\") - \n    (EXTRACT(MINUTE FROM \"timestamp\")::int % 5) * interval '1 minute' AS time,\n  COUNT(1) AS value\nFROM api_usage_metrics\nwhere timestamp between $__timeFrom() and $__timeTo()\nGROUP BY time;\n"
    }
   ]
  },
  {
   "title": "Timeseries of count by teams",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('minute', \"timestamp\") - \n    (EXTRACT(MINUTE FROM \"timestamp\")::int % 5) * interval '1 minute' AS time,\n  b.name AS metric,\n  COUNT(1) AS value\nFROM api_usage_metrics a, teams b\nWHERE timestamp between $__timeFrom() and $__timeTo()\nand a.team_id = b.id\nGROUP BY time, b.name\nORDER BY time, b.name;\n"
    }
   ]
  },
  {
   "title": "Timeseries of count by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('minute', \"timestamp\") - \n    (EXTRACT(MINUTE FROM \"timestamp\")::int % 5) * interval '1 minute' AS time,\n  endpoint AS metric,\n  COUNT(1) AS value\nFROM api_usage_metrics\nWHERE timestamp between $__timeFrom() and $__timeTo()\nGROUP BY time, endpoint\nORDER BY time, endpoint;\n"
    }
   ]
  },
  {
   "title": "API usage by team",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "select a.team_id, b.name, a.method, a.status_code, count(1) from api_usage_metrics a, teams b \nwhere a.team_id = b.id\nand timestamp between $__timeFrom() and $__timeTo() \ngroup by a.team_id, b.name, a.method, a.status_code;"
    }
   ]
  },
  {
   "title": "Count of successful hits to the endpoints",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "select endpoint, count(1) from api_usage_metrics \nwhere status_code >= 200\nand status_code < 400 \nand timestamp > $__timeFrom() \nand timestamp < $__timeTo() \ngroup BY endpoint;"
    }
   ]
  },
  {
   "title": "Count of un-successful hits to the endpoints",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "select endpoint, count(1) from api_usage_metrics \nwhere status_code >= 400 \nand timestamp > $__timeFrom() \nand timestamp < $__timeTo() \ngroup BY endpoint;"
    }
   ]
  }
 ]
}