{
 "title": "Integration Dissect",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "requestId", "query": "select id from requests" }
  ]
 },
 "panels": [
  {
   "title": "Request Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select id, project_name, status, archived as deleted, user_id as requestor, team_id as requesting_team from requests where id=$requestId"
    }
   ]
  },
  {
   "title": "Client Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select client_id, public_access as public_client, auth_type, dev_idps as idps, environments from requests where id=$requestId"
    }
   ]
  },
  {
   "title": "Team Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select r.team_id, t.name, ut.user_id as team_member_id, ut.role, ut.pending as accepted_invite, u.display_name as team_members, u.idir_email from requests r join users_teams ut on r.team_id = ut.team_id join teams t on ut.team_id = t.id join users u on ut.user_id = u.id where r.id=$requestId"
    }
   ]
  },
  {
   "title": "Events Timeline",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select created_at, event_code, details, idir_user_display_name from events where request_id=$requestId order by created_at desc"
    }
   ]
  }
 ]
}