{
 "title": "Search by ID Filter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "(RESOLVED) - Potentially Impacted Roles",
   "type": "table",
   "description": "NOTE: Issue for these is now resolved -- List of roles that were potentially impacted by a deletion error in the CSS DB. Note that this is likely a much larger set than is actually impacted, will have to check in KC to narrow down if any actually were.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with duplicated_roles as (\r\n  select name, environment from request_roles group by name, environment having count(name) > 1 and count(environment) > 1\r\n), potentially_impacted_requests as (\r\n select distinct request_id, duplicated_roles.name as role_name, duplicated_roles.environment as role_env from request_roles join duplicated_roles on request_roles.name = duplicated_roles.name and request_roles.environment = duplicated_roles.environment\r\n) \r\nselect client_id, potentially_impacted_requests.role_name, role_env from requests join potentially_impacted_requests on requests.id = potentially_impacted_requests.request_id where archived=false order by role_name;\r\n-- select * from potentially_impacted_request_ids"
    }
   ]
  },
  { "title": "CSS App Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "rawSql": "SELECT * FROM requests" }
   ]
  },
  {
   "title": "Roles search by request id",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM request_roles r\r\n"
    }
   ]
  },
  {
   "title": "Keycloak Grafana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "Users in certain roles",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "# Go to Grafana keycloak\n\nhere you can find the users in a certain role\nhttps://sso-grafana.apps.gold.devops.gov.bc.ca/d/eee6fb07-e4b2-4be2-b7d8-24dfdeb4fe84/standard-service-roles"
   },
   "targets": [
    {
     "rawSql": "select * from request_roles_temp"
    }
   ]
  }
 ]
}