{
 "title": "Teams",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uses CSS Team Account (Service Account) ONLY PROD",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT r.id AS integration_id,\r\n       r.status,\r\n       t.id AS team_id,\r\n       t.name,\r\n       r.project_name\r\nFROM   requests r,\r\n       users_teams ut,\r\n       teams t\r\nWHERE  r.api_service_account IS TRUE\r\n       AND r.team_id = ut.team_id\r\n       AND ut.team_id = t.id\r\nORDER BY t.id;"
    }
   ]
  },
  {
   "title": "Teams - members and roles",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select ut. role, t.name as team_name, t.id as team_id,  u.idir_email, ut.pending as membership\r\nfrom teams t, users_teams ut, users u\r\nwhere t.id = ut.team_id\r\nAND u.id = ut.user_id\r\norder by t.id;\r\n"
    }
   ]
  },
  {
   "title": "List of Teams and their integrations",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "select r.id as request_id,r.team_id as team_id, t.name, u.idir_email, ut.created_at as invitation_date\r\nfrom requests r, users_teams ut, users u, teams t\r\nwhere r.team_id = ut.team_id\r\nAND u.id = ut.user_id\r\nAND t.id=ut.team_id\r\norder by t.id;"
    }
   ]
  },
  {
   "title": "FilterByIntegrationNumber",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 31 },
   "targets": [
    {
     "rawSql": "select r.id as request_id,r.project_name, r.team_id as team_id, t.name, u.idir_email, ut.role\r\nfrom requests r, users_teams ut, users u, teams t\r\nwhere r.team_id = ut.team_id\r\nAND u.id = ut.user_id\r\nAND t.id=ut.team_id\r\norder by t.id;"
    }
   ]
  },
  {
   "title": "FilterByIntegrationNumberOnlyEmail",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 42 },
   "targets": [
    {
     "rawSql": "select r.id as request_id, u.idir_email\r\nfrom requests r, users_teams ut, users u, teams t\r\nwhere r.team_id = ut.team_id\r\nAND u.id = ut.user_id\r\nAND t.id=ut.team_id\r\norder by t.id;"
    }
   ]
  }
 ]
}