{
 "title": "Timings after Terraform Refactor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "integration_num" }
  ]
 },
 "panels": [
  {
   "title": "Last 7 clients created integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Last 10 clients created - not a service account",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select id, created_at, updated_at from requests  where auth_type not in ('service-account') order by created_at desc  limit 10\r\n--select * from requests order by created_at desc limit 10"
    }
   ]
  },
  {
   "title": "Last 10 clients updated",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select id, updated_at from requests order by updated_at desc  limit 10\r\n-- select * from requests order by created_at desc limit 10"
    }
   ]
  },
  {
   "title": "Single Integration Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Events Description ",
   "type": "text",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 17 },
   "options": {
    "content": "# Events Described\n\n* request-create-success aka Integration saved as draft \n* request-plan-success aka Integration submitted for processing\n* request-apply-success aka Integration is ready to consume\n\n* request-update-success aka Integration updated the DETAILS column will have info\n\n* request-restore-success aka integration restored successfully\n\n\nSequence is\n1. create\n2. plan\n3. apply\n\nat client's discretion\n4. update\n5. delete\n\n\nat sso admin discretion\n6. restore\n"
   }
  },
  {
   "title": "Details of events",
   "type": "table",
   "gridPos": { "h": 14, "w": 19, "x": 5, "y": 17 },
   "targets": [
    {
     "rawSql": "select * \r\nfrom events\r\nwhere  request_id= ${integration_num} \r\n\r\n/* \r\n SELECT r.id, r.project_name,e.details, e.created_at, e.updated_at,e.event_code\r\nFROM requests r, events e\r\nWHERE r.id = ${integration_num}\r\nAND r.id=e.request_id\r\norder by e.created_at asc \r\n\r\n\r\n*/"
    }
   ]
  }
 ]
}