{
 "title": "Account Console Events",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Azureidir account events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select date, count, event_type from client_events_with_idp where client_id in ('account-console', 'account') and realm_id = 'azureidir' and environment = 'prod';"
    }
   ]
  },
  {
   "title": "Idir account events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select date, count, event_type from client_events_with_idp where client_id in ('account-console', 'account') and realm_id = 'idir' and environment = 'prod';"
    }
   ]
  },
  {
   "title": "Basic BCeID account events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select date, count, event_type from client_events_with_idp where client_id in ('account-console', 'account') and realm_id = 'bceidbasic' and environment = 'prod';"
    }
   ]
  },
  {
   "title": "Business BCeID account events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select date, count, event_type from client_events_with_idp where client_id in ('account-console', 'account') and realm_id = 'bceidbusiness' and environment = 'prod';"
    }
   ]
  },
  {
   "title": "Business BCeID account events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select date, count, event_type from client_events_with_idp where client_id in ('account-console', 'account') and realm_id = 'bceidboth' and environment = 'prod';"
    }
   ]
  },
  {
   "title": "Github account events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select date, count, event_type from client_events_with_idp where client_id in ('account-console', 'account') and realm_id = 'github' and environment = 'prod';"
    }
   ]
  },
  {
   "title": "Update profile events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "select date, count, realm_id, event_type from client_events_with_idp where client_id in ('account-console', 'account') and event_type in ('UPDATE_PROFILE', 'UPDATE_PASSWORD', 'UPDATE_CREDENTIAL', 'UPDATE_TOTP') and environment = 'prod';"
    }
   ]
  }
 ]
}