{
 "title": "Active Sessions & SSO Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs by realm",
   "type": "timeseries",
   "description": "A graph of the count of log hits over the past 30 minutes by realm (time is encoded into the panel JSON).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({environment=\"prod\"} |= `realmId=` | regexp \".*realmId=(?P<realmId>\\\\S+),\" [10s])) by (realmId)"
    }
   ]
  },
  {
   "title": "Standard Realm Logs by Client",
   "type": "timeseries",
   "description": "The count of logs over time broken down by client in the standard realm.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({environment=\"prod\"} |= `realmId=standard` | regexp \".*clientId=(?P<clientId>\\\\S+),\" [10s])) by (clientId)"
    }
   ]
  },
  {
   "title": "Number of logins per minute by Month and Year",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT to_char(date, 'YYYY') || '-' || to_char(date, 'Mon') as date, (sum(login)+sum(code_to_token)+sum(refresh_token)+sum(user_info_request)+sum(introspect_token)+sum(client_login)+sum(refresh_token_error))/43800 as rqsts_per_minute FROM sso_stats\ngroup by to_char(date, 'YYYY') || '-' || to_char(date, 'Mon')\norder by date desc;"
    }
   ]
  },
  { "title": "Log Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": {
    "content": "looking at stats based on custom realms having the event logs flag turned on"
   }
  },
  {
   "title": "Details Logs",
   "type": "table",
   "description": "note limit 100",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT * FROM sso_logs \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "# of active sessions in a realm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Useful links",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "- [Cron Job Codebase](https://github.com/bcgov/sso-keycloak/tree/dev/docker/kc-cron-job)"
   }
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 36 },
   "options": {
    "content": "# What does this mean?\n\nLook here if we have any issues with keycloak going down"
   }
  },
  {
   "title": "Details Active Sessions by Client ID",
   "type": "table",
   "description": "note limited to 100",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT  created_at, realm, keycloak_url, client_id, session_count\r\nFROM active_sessions \r\nlimit 100"
    }
   ]
  },
  {
   "title": "Active Sessions by Client ID",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"public\".\"active_sessions\".\"client_id\" AS \"client_id\",\r\n  COUNT(*) AS \"count\"\r\nFROM\r\n  \"public\".\"active_sessions\"\r\nGROUP BY\r\n  \"public\".\"active_sessions\".\"client_id\"\r\nORDER BY\r\n  \"public\".\"active_sessions\".\"client_id\" ASC"
    }
   ]
  },
  {
   "title": "Details Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    { "rawSql": "SELECT * FROM sso_stats " }
   ]
  }
 ]
}