{
 "title": "Digital Credential User Counts",
 "description": "This dashboard only looks at Custom and Standard Realm Users",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "DC users from Standard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prod Number of DC standard users in by standard client.",
   "type": "table",
   "description": "Every standard client has a standard role associated with it.  Counting these allows us to count the number of VC users per client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\nkeycloak_role.name AS \"Standard Client\",\r\nCOUNT(federated_identity.federated_username) AS \"Number of Role Users\"\r\nFROM federated_identity\r\nINNER JOIN user_role_mapping ON (federated_identity.user_id = user_role_mapping.user_id)\r\nINNER JOIN keycloak_role ON (user_role_mapping.role_id = keycloak_role.id)\r\nWHERE federated_identity.realm_id = 'standard'\r\nAND federated_identity.identity_provider = 'digitalcredential'\r\nAND keycloak_role.name != 'default-roles-standard'\r\nGROUP BY keycloak_role.name\r\nORDER BY COUNT(federated_identity.federated_username)"
    }
   ]
  },
  {
   "title": "Test Number of DC standard users in by standard client.",
   "type": "table",
   "description": "Every standard client has a standard role associated with it.  Counting these allows us to count the number of VC users per client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \r\nkeycloak_role.name AS \"Standard Client\",\r\nCOUNT(federated_identity.federated_username) AS \"Number of Role Users\"\r\nFROM federated_identity\r\nINNER JOIN user_role_mapping ON (federated_identity.user_id = user_role_mapping.user_id)\r\nINNER JOIN keycloak_role ON (user_role_mapping.role_id = keycloak_role.id)\r\nWHERE federated_identity.realm_id = 'standard'\r\nAND federated_identity.identity_provider = 'digitalcredential'\r\nAND keycloak_role.name != 'default-roles-standard'\r\nGROUP BY keycloak_role.name\r\nORDER BY COUNT(federated_identity.federated_username)"
    }
   ]
  },
  {
   "title": "Dev Number of DC standard users in by standard client.",
   "type": "table",
   "description": "Every standard client has a standard role associated with it.  Counting these allows us to count the number of VC users per client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \r\nkeycloak_role.name AS \"Standard Client\",\r\nCOUNT(federated_identity.federated_username) AS \"Number of Role Users\"\r\nFROM federated_identity\r\nINNER JOIN user_role_mapping ON (federated_identity.user_id = user_role_mapping.user_id)\r\nINNER JOIN keycloak_role ON (user_role_mapping.role_id = keycloak_role.id)\r\nWHERE federated_identity.realm_id = 'standard'\r\nAND federated_identity.identity_provider = 'digitalcredential'\r\nAND keycloak_role.name != 'default-roles-standard'\r\nGROUP BY keycloak_role.name\r\nORDER BY COUNT(federated_identity.federated_username)"
    }
   ]
  },
  {
   "title": "Custom Realm  DC Users via CSS standard Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prod Standard Digital Crendential User Counts",
     "type": "timeseries",
     "description": "This counts the DC users in each custom realmthat rely on a standard realm client.",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT realm_id, count(*)\r\nfrom federated_identity \r\nwhere federated_username like '%@digitalcredential%'\r\n-- AND realm_id not in ('digitalcredential', 'standard')\r\ngroup by realm_id\r\norder by count(*) desc;"
      }
     ]
    },
    {
     "title": "Test Standard Digital Crendential User Counts",
     "type": "timeseries",
     "description": "This counts the DC users in each custom realmthat rely on a standard realm client.",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT realm_id, count(*)\r\nfrom federated_identity \r\nwhere federated_username like '%@digitalcredential%'\r\n-- AND realm_id not in ('digitalcredential', 'standard')\r\ngroup by realm_id\r\norder by count(*) desc;"
      }
     ]
    },
    {
     "title": "Dev Standard Digital Crendential User Counts",
     "type": "timeseries",
     "description": "This counts the DC users in each custom realmthat rely on a standard realm client.",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT realm_id, count(*)\r\nfrom federated_identity \r\nwhere federated_username like '%@digitalcredential%'\r\n-- AND realm_id not in ('digitalcredential', 'standard')\r\ngroup by realm_id\r\norder by count(*) desc;"
      }
     ]
    }
   ]
  },
  {
   "title": "Custom Realms direct VC integration and user counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prod Custom User Count with Direct VC integration",
     "type": "table",
     "description": "User count for custom realm VC users that integrate directly with `vc-auth-oidc`",
     "gridPos": { "h": 8, "w": 5, "x": 1, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT \r\nidentity_provider.realm_id, \r\nCOUNT(federated_identity.user_id) \r\nFROM identity_provider_config \r\nINNER JOIN identity_provider ON (identity_provider_config.identity_provider_id = identity_provider.internal_id)\r\nINNER JOIN federated_identity ON (identity_provider.realm_id = federated_identity.realm_id)\r\nWHERE identity_provider_config.name LIKE '%authorizationUrl%' \r\nAND identity_provider_config.value LIKE '%vc-authn-oidc%' \r\nAND federated_identity.identity_provider = identity_provider.provider_alias \r\nAND identity_provider.realm_id not in ('digitalcredential')\r\nGROUP BY identity_provider.realm_id\r\norder BY COUNT(federated_identity.user_id)\r\nLIMIT 50 "
      }
     ]
    },
    {
     "title": "Prod Realms that use vc-auth url",
     "type": "table",
     "description": "A list of realms that have an IDP connecting directly to 'vc--auth-urls'",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT \r\nrealm_id as \"Realm\", \r\nvalue as \"Authorization Url\"\r\nFROM identity_provider_config \r\nINNER JOIN identity_provider ON (identity_provider_config.identity_provider_id = identity_provider.internal_id)\r\nWHERE identity_provider_config.name LIKE '%authorizationUrl%' and identity_provider_config.value LIKE '%vc-authn-oidc%'\r\nLIMIT 50 "
      }
     ]
    },
    {
     "title": "Test Custom User Count with Direct VC integration",
     "type": "table",
     "description": "User count for custom realm VC users that integrate directly with `vc-auth-oidc`",
     "gridPos": { "h": 8, "w": 5, "x": 1, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT \r\nidentity_provider.realm_id, \r\nCOUNT(federated_identity.user_id) \r\nFROM identity_provider_config \r\nINNER JOIN identity_provider ON (identity_provider_config.identity_provider_id = identity_provider.internal_id)\r\nINNER JOIN federated_identity ON (identity_provider.realm_id = federated_identity.realm_id)\r\nWHERE identity_provider_config.name LIKE '%authorizationUrl%' \r\nAND identity_provider_config.value LIKE '%vc-authn-oidc%' \r\nAND federated_identity.identity_provider = identity_provider.provider_alias \r\nAND identity_provider.realm_id not in ('digitalcredential')\r\nGROUP BY identity_provider.realm_id\r\norder BY COUNT(federated_identity.user_id)\r\nLIMIT 50 "
      }
     ]
    },
    {
     "title": "Test Realms that use vc-auth url",
     "type": "table",
     "description": "A list of realms that have an IDP connecting directly to 'vc--auth-urls'",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT \r\nrealm_id as \"Realm\", \r\nvalue as \"Authorization Url\"\r\nFROM identity_provider_config \r\nINNER JOIN identity_provider ON (identity_provider_config.identity_provider_id = identity_provider.internal_id)\r\nWHERE identity_provider_config.name LIKE '%authorizationUrl%' and identity_provider_config.value LIKE '%vc-authn-oidc%'\r\nLIMIT 50 "
      }
     ]
    },
    {
     "title": "Dev Custom User Count with Direct VC integration",
     "type": "table",
     "description": "User count for custom realm VC users that integrate directly with `vc-auth-oidc`",
     "gridPos": { "h": 8, "w": 5, "x": 1, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT \r\nidentity_provider.realm_id, \r\nCOUNT(federated_identity.user_id) \r\nFROM identity_provider_config \r\nINNER JOIN identity_provider ON (identity_provider_config.identity_provider_id = identity_provider.internal_id)\r\nINNER JOIN federated_identity ON (identity_provider.realm_id = federated_identity.realm_id)\r\nWHERE identity_provider_config.name LIKE '%authorizationUrl%' \r\nAND identity_provider_config.value LIKE '%vc-authn-oidc%' \r\nAND federated_identity.identity_provider = identity_provider.provider_alias \r\nAND identity_provider.realm_id not in ('digitalcredential')\r\nGROUP BY identity_provider.realm_id\r\norder BY COUNT(federated_identity.user_id)\r\nLIMIT 50 "
      }
     ]
    },
    {
     "title": "Dev Realms that  use vc-auth url ",
     "type": "table",
     "description": "A list of realms that have an IDP connecting directly to 'vc--auth-urls'",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT \r\nrealm_id as \"Realm\", \r\nvalue as \"Authorization Url\"\r\nFROM identity_provider_config \r\nINNER JOIN identity_provider ON (identity_provider_config.identity_provider_id = identity_provider.internal_id)\r\nWHERE identity_provider_config.name LIKE '%authorizationUrl%' and identity_provider_config.value LIKE '%vc-authn-oidc%'\r\nLIMIT 50 "
      }
     ]
    }
   ]
  }
 ]
}