{
 "title": "Event counts by client",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "date",
    "label": "Date",
    "query": "select distinct to_char(date, 'YYYY-MM-DD') from client_events"
   },
   {
    "name": "count",
    "label": "Count",
    "query": "500,1000,2000,5000,10000,15000,20000,25000"
   },
   {
    "name": "event",
    "label": "Event",
    "query": "select distinct event_type from client_events where count > ${count} and to_char(date, 'YYYY-MM-DD')='${date}';"
   }
  ]
 },
 "panels": [
  {
   "title": "Clients login counts by date",
   "type": "barchart",
   "description": "Clients with more than ${count} logins on ${date}",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select client_id,sum(count) as \"Total\" FROM client_events_with_idp where to_char(date, 'YYYY-MM-DD')='${date}' and event_type='${event}' and count > ${count} and client_id not in ('admin-cli', 'security-admin-console')\ngroup by client_id order by client_id asc"
    }
   ]
  },
  {
   "title": "Count of events in time range",
   "type": "timeseries",
   "description": "Count of events in the set time range",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "select date, client_id, count from client_events_with_idp where event_type='${event}' and date > $__timeFrom() and date < $__timeTo() and count > $count "
    }
   ]
  },
  {
   "title": "Clients by all events 6 months",
   "type": "table",
   "description": "Clients ordered by total event count going back all recorded time (6 months)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "select sum(count) as total, realm_id, client_id from client_events_with_idp group by realm_id, client_id order by total desc;"
    }
   ]
  }
 ]
}