{
 "title": "Inactive IDIR",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Deactivated IDIRs",
   "type": "table",
   "description": "across all 3 envs: DEV, TEST, PROD",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select to_char(timestamp, 'YYYY-MM-DD') as date_deleted,  count (*)\r\nfrom kc_deleted_users \r\nGROUP BY to_char(timestamp, 'YYYY-MM-DD') \r\norder by to_char(timestamp, 'YYYY-MM-DD') DESC"
    }
   ]
  },
  {
   "title": "All deleted users",
   "type": "table",
   "description": "A list of all deleted users over the last 30 days",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp, environment, email, first_name, last_name\r\nfrom kc_deleted_users\r\norder by timestamp desc, email desc;"
    }
   ]
  },
  {
   "title": "Deleted Users With Client Roles",
   "type": "table",
   "description": "Shows users with client role information. Only includes users with client roles.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select timestamp, environment, email, first_name, last_name, jsonb_pretty(value::jsonb) AS \"Client Roles\" \r\nfrom kc_deleted_users, unnest(client_roles) as value\r\nwhere client_roles::text <> '{}'::text\r\norder by timestamp desc, email desc;"
    }
   ]
  }
 ]
}