{
 "title": "Standard Service Roles",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "roles limited to 10",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dev Roles",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\r\n\"Client\".\"client_id\" AS \"Client__client_id\",\r\n  \"Keycloak Role\".\"client_role\" AS \"Keycloak Role__client_role\",\r\n  \"Keycloak Role\".\"description\" AS \"Keycloak Role__description\",\r\n    \"Keycloak Role\".\"name\" AS \"Keycloak Role__name\",\r\n  \"Keycloak Role\".\"realm_id\" AS \"Keycloak Role__realm_id\",\r\n  \"public\".\"user_entity\".\"first_name\" AS \"first_name\",\r\n  \"public\".\"user_entity\".\"last_name\" AS \"last_name\",\r\n  \"public\".\"user_entity\".\"realm_id\" AS \"realm_id\",\r\n  \"public\".\"user_entity\".\"username\" AS \"username\",\r\n  \"public\".\"user_entity\".\"id\" AS \"id\",\r\n  \r\n\r\n  \"Keycloak Role\".\"realm\" AS \"Keycloak Role__realm\"\r\n  \r\nFROM\r\n  \"public\".\"user_entity\"\r\n \r\nLEFT JOIN \"public\".\"user_role_mapping\" AS \"User Role Mapping\" ON \"public\".\"user_entity\".\"id\" = \"User Role Mapping\".\"user_id\"\r\n  LEFT JOIN \"public\".\"keycloak_role\" AS \"Keycloak Role\" ON \"User Role Mapping\".\"role_id\" = \"Keycloak Role\".\"id\"\r\n  LEFT JOIN \"public\".\"client\" AS \"Client\" ON \"Keycloak Role\".\"client\" = \"Client\".\"id\"\r\nWHERE\r\n  \"public\".\"user_entity\".\"realm_id\" = 'standard'\r\n\r\n  limit 10"
      }
     ]
    },
    {
     "title": "PROD  Roles",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\r\n\"Client\".\"client_id\" AS \"Client__client_id\",\r\n  \"Keycloak Role\".\"client_role\" AS \"Keycloak Role__client_role\",\r\n  \"Keycloak Role\".\"description\" AS \"Keycloak Role__description\",\r\n    \"Keycloak Role\".\"name\" AS \"Keycloak Role__name\",\r\n  \"Keycloak Role\".\"realm_id\" AS \"Keycloak Role__realm_id\",\r\n  \"public\".\"user_entity\".\"first_name\" AS \"first_name\",\r\n  \"public\".\"user_entity\".\"last_name\" AS \"last_name\",\r\n  \"public\".\"user_entity\".\"realm_id\" AS \"realm_id\",\r\n  \"public\".\"user_entity\".\"username\" AS \"username\",\r\n  \"public\".\"user_entity\".\"id\" AS \"id\",\r\n  \r\n\r\n  \"Keycloak Role\".\"realm\" AS \"Keycloak Role__realm\"\r\n  \r\nFROM\r\n  \"public\".\"user_entity\"\r\n \r\nLEFT JOIN \"public\".\"user_role_mapping\" AS \"User Role Mapping\" ON \"public\".\"user_entity\".\"id\" = \"User Role Mapping\".\"user_id\"\r\n  LEFT JOIN \"public\".\"keycloak_role\" AS \"Keycloak Role\" ON \"User Role Mapping\".\"role_id\" = \"Keycloak Role\".\"id\"\r\n  LEFT JOIN \"public\".\"client\" AS \"Client\" ON \"Keycloak Role\".\"client\" = \"Client\".\"id\"\r\nWHERE\r\n  \"public\".\"user_entity\".\"realm_id\" = 'standard'\r\n\r\n  limit 10"
      }
     ]
    }
   ]
  },
  {
   "title": "All Roles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "Customize env and query parm",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\r\nc.client_id AS \"Client__client_id\",\r\nkr.client_role AS \"Keycloak Role__client_role\",\r\nkr.description AS \"Keycloak Role__description\",\r\nkr.name AS \"Keycloak Role__name\",\r\nkr.realm_id AS \"Keycloak Role__realm_id\",\r\nue.first_name AS \"first_name\",\r\nue.last_name  AS \"last_name\",\r\nue.username AS \"username\"\r\n\r\nFROM \r\nuser_entity as ue,\r\nuser_role_mapping as urm,\r\nkeycloak_role as kr,\r\nclient as c\r\n\r\nWHERE\r\n\r\nurm.user_id=ue.id AND\r\nkr.id = urm.role_id AND\r\nkr.client = c.id AND\r\n\r\nue.realm_id='standard' AND c.client_id like '%4414%'\r\n"
    }
   ]
  },
  {
   "title": "By Email Address OR GUID",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "email: Customize env and query parm",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\nc.client_id AS \"Client__client_id\",\r\nkr.client_role AS \"Keycloak Role__client_role\",\r\nkr.description AS \"Keycloak Role__description\",\r\nkr.name AS \"Keycloak Role__name\",\r\nkr.realm_id AS \"Keycloak Role__realm_id\",\r\nue.email as \"email\",\r\nue.first_name AS \"first_name\",\r\nue.last_name  AS \"last_name\",\r\nue.username AS \"username\"\r\n\r\n\r\nFROM \r\nuser_entity as ue,\r\nuser_role_mapping as urm,\r\nkeycloak_role as kr,\r\nclient as c\r\n\r\nWHERE\r\n\r\nurm.user_id=ue.id AND\r\nkr.id = urm.role_id AND\r\nkr.client = c.id AND\r\n\r\n\r\nue.realm_id='standard' \r\nAND \r\nue.email like 'mhruby@conumacoal.com'\r\n"
    }
   ]
  },
  {
   "title": "guid: Customize env and query parm",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\nc.client_id AS \"Client__client_id\",\r\nkr.client_role AS \"Keycloak Role__client_role\",\r\nkr.description AS \"Keycloak Role__description\",\r\nkr.name AS \"Keycloak Role__name\",\r\nkr.realm_id AS \"Keycloak Role__realm_id\",\r\nue.email as \"email\",\r\nue.first_name AS \"first_name\",\r\nue.last_name  AS \"last_name\",\r\nue.username AS \"username\"\r\n\r\n\r\nFROM \r\nuser_entity as ue,\r\nuser_role_mapping as urm,\r\nkeycloak_role as kr,\r\nclient as c\r\n\r\nWHERE\r\n\r\nurm.user_id=ue.id AND\r\nkr.id = urm.role_id AND\r\nkr.client = c.id AND\r\nue.realm_id='standard' AND\r\nue.username = '88405ee5bc6d4d57979b489d1f1caf4d@bceidboth'  \r\n--OR ue.username = 'a8b9acc02a934e21b32fb0e178e2f26c@bceidboth'\r\n"
    }
   ]
  }
 ]
}