{
 "title": "Events",
 "description": "Some CSS App event stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Log Downloads Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from events where event_code = 'logs-download-success';"
    }
   ]
  },
  {
   "title": "Failed Downloads (Excluding Timeouts)",
   "type": "stat",
   "description": "Count of failed log downloads. When loki times out, the lambda code stops execution preventing this log count. To see all failures best to use cloudwatch instead.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from events where event_code = 'logs-download-failure';"
    }
   ]
  },
  {
   "title": "Log Download Event ",
   "type": "table",
   "description": "A count of the attempts to download logs by client id",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "select client_id, count(request_id) as event_count from events join requests on requests.id = events.request_id where event_code ilike 'logs-download-%' group by request_id, client_id order by event_count desc;"
    }
   ]
  }
 ]
}