{
 "title": "Primary end users by IDPs",
 "description": "Displays count of different primary end users by identity providers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "idps",
    "label": "IDPS",
    "query": "idir,bceidbasic,bceidbusiness,bceidboth,bcservicescard,otp,digitalcredential,githubbcgov,githubpublic"
   }
  ]
 },
 "panels": [
  {
   "title": "Primary end users by IDP",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\naud AS audience,\nCOUNT(*) AS row_count\nFROM requests\nCROSS JOIN LATERAL unnest(primary_end_users) AS aud\nWHERE dev_idps @> ARRAY[$idps]::varchar[]\nAND status = 'applied' AND archived = false\nGROUP BY aud\nUNION ALL\nSELECT\n'null' AS audience,\nCOUNT(*) AS row_count\nFROM requests\nWHERE dev_idps @> ARRAY[$idps]::varchar[]\nAND status = 'applied' AND archived = false\nAND (primary_end_users is NULL OR primary_end_users = '{}'::text[]);"
    }
   ]
  },
  {
   "title": "Count of active integrations by IDPs",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \ncount(*) AS total\nFROM requests\nWHERE dev_idps @> ARRAY[$idps]::varchar[]\nAND status = 'applied' AND archived = false"
    }
   ]
  },
  {
   "title": "Primary end users by idp counts",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\naud AS audience,\nCOUNT(*) AS row_count\nFROM requests\nCROSS JOIN LATERAL unnest(primary_end_users) AS aud\nWHERE dev_idps @> ARRAY[$idps]::varchar[]\nAND status = 'applied' AND archived = false\nGROUP BY aud\nUNION ALL\nSELECT\n'null' AS audience,\nCOUNT(*) AS row_count\nFROM requests\nWHERE dev_idps @> ARRAY[$idps]::varchar[]\nAND status = 'applied' AND archived = false\nAND (primary_end_users is NULL OR primary_end_users = '{}'::text[]);"
    }
   ]
  },
  {
   "title": "Average days for BCeID Basic approval",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH per_request AS (\n    SELECT\n        request_id,\n        MIN(created_at) FILTER (\n            WHERE details -> 'changes' @> '[{\n  \"item\": {\n    \"rhs\": \"bceidbasic\",\n    \"kind\": \"N\"\n  },\n  \"kind\": \"A\",\n  \"path\": [\"devIdps\"]\n}]'\n        ) AS created_at,\n        MAX(created_at) FILTER (\n            WHERE details::text ILIKE '%bceidApproved%'\n        ) AS approved_at\n    FROM events\n    GROUP BY request_id\n)\nSELECT\n    ROUND(\n        AVG(EXTRACT(EPOCH FROM (approved_at - created_at))) / 86400,\n        2\n    ) AS avg_time_days\nFROM per_request\nWHERE created_at IS NOT NULL\n  AND approved_at IS NOT NULL\n  AND approved_at > created_at;"
    }
   ]
  },
  {
   "title": "Average days for BCeID Business approval",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH per_request AS (\n    SELECT\n        request_id,\n        MIN(created_at) FILTER (\n            WHERE details -> 'changes' @> '[{\n  \"item\": {\n    \"rhs\": \"bceidbusiness\",\n    \"kind\": \"N\"\n  },\n  \"kind\": \"A\",\n  \"path\": [\"devIdps\"]\n}]'\n        ) AS created_at,\n        MAX(created_at) FILTER (\n            WHERE details::text ILIKE '%bceidApproved%'\n        ) AS approved_at\n    FROM events\n    GROUP BY request_id\n)\nSELECT\n    ROUND(\n        AVG(EXTRACT(EPOCH FROM (approved_at - created_at))) / 86400,\n        2\n    ) AS avg_time_days\nFROM per_request\nWHERE created_at IS NOT NULL\n  AND approved_at IS NOT NULL\n  AND approved_at > created_at;"
    }
   ]
  },
  {
   "title": "Average days for BCeID Both approval",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH per_request AS (\n    SELECT\n        request_id,\n        MIN(created_at) FILTER (\n            WHERE details -> 'changes' @> '[{\n  \"item\": {\n    \"rhs\": \"bceidboth\",\n    \"kind\": \"N\"\n  },\n  \"kind\": \"A\",\n  \"path\": [\"devIdps\"]\n}]'\n        ) AS created_at,\n        MAX(created_at) FILTER (\n            WHERE details::text ILIKE '%bceidApproved%'\n        ) AS approved_at\n    FROM events\n    GROUP BY request_id\n)\nSELECT\n    ROUND(\n        AVG(EXTRACT(EPOCH FROM (approved_at - created_at))) / 86400,\n        2\n    ) AS avg_time_days\nFROM per_request\nWHERE created_at IS NOT NULL\n  AND approved_at IS NOT NULL\n  AND approved_at > created_at;"
    }
   ]
  },
  {
   "title": "Average days for BC Services Card approval",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH per_request AS (\n    SELECT\n        request_id,\n        MIN(created_at) FILTER (\n            WHERE details -> 'changes' @> '[{\n  \"item\": {\n    \"rhs\": \"bcservicescard\",\n    \"kind\": \"N\"\n  },\n  \"kind\": \"A\",\n  \"path\": [\"devIdps\"]\n}]'\n        ) AS created_at,\n        MAX(created_at) FILTER (\n            WHERE details::text ILIKE '%bcservicescardApproved%'\n        ) AS approved_at\n    FROM events\n    GROUP BY request_id\n)\nSELECT\n    ROUND(\n        AVG(EXTRACT(EPOCH FROM (approved_at - created_at))) / 86400,\n        2\n    ) AS avg_time_days\nFROM per_request\nWHERE created_at IS NOT NULL\n  AND approved_at IS NOT NULL\n  AND approved_at > created_at;"
    }
   ]
  }
 ]
}